name: Android Tests with Fastlane

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Android Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Ruby and Install Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: gem install fastlane -NV

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: fastlane android test
